#!/bin/bash

# Polygon
ETHERSCAN_KEY=
STAGE=prod
DEPLOYED_CONTRACT_ADDRESS=
CHAIN_ID=
CHAIN_ID=$CHAIN_ID ETHERSCAN_API_KEY=$ETHERSCAN_KEY npx hardhat verify --network $STAGE $DEPLOYED_CONTRACT_ADDRESS
